### GET CLIENTES
GET http://localhost:8081/api/v1/clientes


### POST CLIENTES
POST http://localhost:8081/api/v1/clientes
Content-Type: application/json

{
    "nome": "zezinho",
    "endereco": "Rua lalalalla 100",
    "dataNascimento": "2024-10-01"
}

### PUT CLIENTES
PUT http://localhost:8081/api/v1/clientes/1
Content-Type: application/json

{
    "nome": "zezinho da Silva Sauro",
    "endereco": "Rua lalalalla 200",
    "dataNascimento": "2024-10-01"
}

### DELETE CLIENTES
DELETE http://localhost:8081/api/v1/clientes/1
Content-Type: application/json